
IS_SESSION_INITIALIZED = "IS_SESSION_INITIALIZED"

OUTPUT_KEY_ROOT_AGENT = "OUTPUT_KEY_ROOT_AGENT"

IS_EXPERT_AGENT_USED = "IS_EXPERT_AGENT_USED"
EXPERT_AGENT_PYTHON_REPL_FUNC_USES = "EXPERT_AGENT_PYTHON_REPL_FUNC_USES"
EXPERT_AGENT_PYTHON_REPL_FUNC_MAX_USES = "EXPERT_AGENT_PYTHON_REPL_FUNC_MAX_USES"
EXPERT_AGENT_PYTHON_REPL_FUNC_MAX_TOKENS = "EXPERT_AGENT_PYTHON_REPL_FUNC_MAX_TOKENS"
EXPERT_AGENT_CODE_RAG_USES = "EXPERT_AGENT_CODE_RAG_USES"
EXPERT_AGENT_CODE_RAG_MAX_USES = "EXPERT_AGENT_CODE_RAG_MAX_USES"
EXPERT_AGENT_CODE_BLOCK = "EXPERT_AGENT_CODE_BLOCK"
EXPERT_AGENT_PAPER_RAG_USES = "EXPERT_AGENT_PAPER_RAG_USES"
EXPERT_AGENT_PAPER_RAG_MAX_USES = "EXPERT_AGENT_PAPER_RAG_MAX_USES"
EXPERT_AGENT_PAPER_CONTENT = "EXPERT_AGENT_PAPER_CONTENT"
EXPERT_AGENT_START_TIME = "EXPERT_AGENT_START_TIME"
OUTPUT_KEY_EXPERT_AGENT = "OUTPUT_KEY_EXPERT_AGENT"

MODELS_DICTIONARY = "MODELS_DICTIONARY"
MODEL_VERSIONS = "MODEL_VERSIONS"
IS_MODELS_DICTIONARY_AVAILABLE = "IS_MODELS_DICTIONARY_AVAILABLE"
IS_MODELS_CODE_AVAILABLE = "IS_MODELS_CODE_AVAILABLE"
IS_MODELS_PAPER_AVAILABLE = "IS_MODELS_PAPER_AVAILABLE"

CFG = "CFG"

TMP_ROOT_FOLDER = "tmp"
TMP_MODEL_OBJECT_FOLDER = "tmp/model_objects"


# NOT reset within a session
PERSISTENT_STATES = {
    IS_SESSION_INITIALIZED: False,
    OUTPUT_KEY_ROOT_AGENT: "",
    EXPERT_AGENT_PYTHON_REPL_FUNC_MAX_USES: 5,
    EXPERT_AGENT_PYTHON_REPL_FUNC_MAX_TOKENS: 10000,
    EXPERT_AGENT_CODE_RAG_MAX_USES: 1,
    EXPERT_AGENT_CODE_BLOCK: "",
    EXPERT_AGENT_PAPER_RAG_MAX_USES: 1,
    EXPERT_AGENT_PAPER_CONTENT: "",
    OUTPUT_KEY_EXPERT_AGENT: "",
    MODELS_DICTIONARY: {},
    MODEL_VERSIONS: [],
    IS_MODELS_DICTIONARY_AVAILABLE: False,
    IS_MODELS_CODE_AVAILABLE: False,
    IS_MODELS_PAPER_AVAILABLE: False,
    CFG: {},
}


# reset for every query
TEMPORARY_STATES = {
    IS_EXPERT_AGENT_USED: False,
    EXPERT_AGENT_PYTHON_REPL_FUNC_USES: 5,
    EXPERT_AGENT_CODE_RAG_USES: 1,
    EXPERT_AGENT_PAPER_RAG_USES: 1,
    EXPERT_AGENT_START_TIME: None,
}
    
