

IS_SESSION_INITIALIZED = "IS_SESSION_INITIALIZED"

USER_QUERY = "USER_QUERY"
CURRENT_SELECTED_MODEL = "CURRENT_SELECTED_MODEL"
CURRENT_SELECTED_MODEL_INFO = "CURRENT_SELECTED_MODEL_INFO"
ANALYSIS_PROMPT_CONTENT = "ANALYSIS_PROMPT_CONTENT"

OUTPUT_KEY_ROOT_AGENT = "OUTPUT_KEY_ROOT_AGENT"

EXPERT_AGENT_USES = "EXPERT_AGENT_USES"
EXPERT_AGENT_MAX_USES = "EXPERT_AGENT_MAX_USES"
CURRENT_ANALYSIS_TYPE = "CURRENT_ANALYSIS_TYPE"
EXPERT_AGENT_PYTHON_REPL_FUNC_USES = "EXPERT_AGENT_PYTHON_REPL_FUNC_USES"
EXPERT_AGENT_PYTHON_REPL_FUNC_MAX_USES = "EXPERT_AGENT_PYTHON_REPL_FUNC_MAX_USES"
EXPERT_AGENT_PYTHON_REPL_FUNC_MAX_TOKENS = "EXPERT_AGENT_PYTHON_REPL_FUNC_MAX_TOKENS"
EXPERT_AGENT_GET_MODEL_COMPONENTS_MAX_TOKENS = "EXPERT_AGENT_GET_MODEL_COMPONENTS_MAX_TOKENS"
EXPERT_AGENT_CODE_RAG_USES = "EXPERT_AGENT_CODE_RAG_USES"
EXPERT_AGENT_CODE_RAG_MAX_USES = "EXPERT_AGENT_CODE_RAG_MAX_USES"
EXPERT_AGENT_CODE_BLOCK = "EXPERT_AGENT_CODE_BLOCK"
EXPERT_AGENT_PAPER_RAG_USES = "EXPERT_AGENT_PAPER_RAG_USES"
EXPERT_AGENT_PAPER_RAG_MAX_USES = "EXPERT_AGENT_PAPER_RAG_MAX_USES"
EXPERT_AGENT_PAPER_CONTENT = "EXPERT_AGENT_PAPER_CONTENT"
EXPERT_AGENT_START_TIME = "EXPERT_AGENT_START_TIME"
OUTPUT_KEY_EXPERT_AGENT = "OUTPUT_KEY_EXPERT_AGENT"

ILLUSTRATOR_AGENT_GET_MODEL_INFO_FOR_DESCRIPTION_USES = "ILLUSTRATOR_AGENT_GET_MODEL_INFO_FOR_DESCRIPTION_USES"
ILLUSTRATOR_AGENT_GET_MODEL_INFO_FOR_DESCRIPTION_MAX_TOKENS = "ILLUSTRATOR_AGENT_GET_MODEL_INFO_FOR_DESCRIPTION_MAX_TOKENS"

MODELS_DICTIONARY = "MODELS_DICTIONARY"
MODEL_VERSIONS = "MODEL_VERSIONS"
HISTORICAL_MODELS_METADATA = "HISTORICAL_MODELS_METADATA"
IS_MODELS_DICTIONARY_AVAILABLE = "IS_MODELS_DICTIONARY_AVAILABLE"
IS_MODELS_CODE_AVAILABLE = "IS_MODELS_CODE_AVAILABLE"
IS_MODELS_PAPER_AVAILABLE = "IS_MODELS_PAPER_AVAILABLE"
SYNTHETIC_PAPER_GENERATED = "SYNTHETIC_PAPER_GENERATED"
NEED_SYNTHETIC_PAPER = "NEED_SYNTHETIC_PAPER"
MODEL_FOR_PAPER_GENERATION = "MODEL_FOR_PAPER_GENERATION"
HAS_INFEASIBILITY_DIAGNOSIS = "HAS_INFEASIBILITY_DIAGNOSIS"
INFEASIBILITY_DIAGNOSIS = "INFEASIBILITY_DIAGNOSIS"

# Generator agent output keys
CODER_1_OUTPUT = "CODER_1_OUTPUT"
CODER_2_OUTPUT = "CODER_2_OUTPUT"
CODER_3_OUTPUT = "CODER_3_OUTPUT"
GENERATOR_OUTPUT = "GENERATOR_OUTPUT"

# Cache for get_model_components results
MODEL_COMPONENTS_CACHE = "MODEL_COMPONENTS_CACHE"
MAX_CACHE_ENTRIES = 50

# Timing tracking state keys
LLM_CALL_COUNTER = "LLM_CALL_COUNTER"
TOOL_CALL_START_TIME = "TOOL_CALL_START_TIME"
LLM_CALL_START_TIME = "LLM_CALL_START_TIME"

CFG = "CFG"

TMP_ROOT_FOLDER = "tmp"
TMP_MODEL_OBJECT_FOLDER = "tmp/model_objects"
TMP_MODEL_DATA_FOLDER = "tmp/model_objects/data"
TMP_ROBUST_FOLDER = "tmp/robust"
METADATA_FILE_PATH = "tmp/model_objects/metadata.json"


# NOT reset within a session
PERSISTENT_STATES = {
    IS_SESSION_INITIALIZED: False,
    OUTPUT_KEY_ROOT_AGENT: "",
    EXPERT_AGENT_MAX_USES: 5,
    EXPERT_AGENT_PYTHON_REPL_FUNC_MAX_USES: 5,
    EXPERT_AGENT_PYTHON_REPL_FUNC_MAX_TOKENS: 10000,
    EXPERT_AGENT_CODE_RAG_MAX_USES: 1,
    EXPERT_AGENT_CODE_BLOCK: "",
    EXPERT_AGENT_PAPER_RAG_MAX_USES: 1,
    EXPERT_AGENT_PAPER_CONTENT: "",
    OUTPUT_KEY_EXPERT_AGENT: "",
    ILLUSTRATOR_AGENT_GET_MODEL_INFO_FOR_DESCRIPTION_MAX_TOKENS: 10000, 
    MODELS_DICTIONARY: {},
    MODEL_VERSIONS: [],
    HISTORICAL_MODELS_METADATA: {},
    IS_MODELS_DICTIONARY_AVAILABLE: False,
    IS_MODELS_CODE_AVAILABLE: False,
    IS_MODELS_PAPER_AVAILABLE: False,
    SYNTHETIC_PAPER_GENERATED: False,
    NEED_SYNTHETIC_PAPER: False,
    MODEL_FOR_PAPER_GENERATION: "",
    HAS_INFEASIBILITY_DIAGNOSIS: False,
    INFEASIBILITY_DIAGNOSIS: {},
    CURRENT_SELECTED_MODEL: [],
    CURRENT_SELECTED_MODEL_INFO: "(none)",
    ANALYSIS_PROMPT_CONTENT: "",
    CFG: {},
    "MODELS_METADATA_FORMATTED": "    No models available",
    "SYNTHETIC_PAPER_NOTE": "",
}


# reset for every query
TEMPORARY_STATES = {
    USER_QUERY: "",
    CURRENT_ANALYSIS_TYPE: "RETRIEVAL",
    EXPERT_AGENT_USES: 0,
    EXPERT_AGENT_PYTHON_REPL_FUNC_USES: 3,
    EXPERT_AGENT_CODE_RAG_USES: 1,
    EXPERT_AGENT_PAPER_RAG_USES: 1,
    EXPERT_AGENT_START_TIME: False,
    LLM_CALL_COUNTER: {},  # {agent_name: call_count}
    TOOL_CALL_START_TIME: None,
    LLM_CALL_START_TIME: None,
}
    
